
import logging
import logging.config
import os
import sys
from time import time

import pandas as pd

sys.path.append('../')
from pathlib import Path
import scraper.configuration as config

# Initialize and configure the logger
logging.config.dictConfig(config.LOGGING_CONFIG)
logger = logging.getLogger("Scraping log")

MERGED_DATA_PKL = Path("data/merged_data.pkl") # From Git
PIPELINE_OUTPUT_CSV = Path("scrape_job_output.csv")
PIPELINE_OUTPUT_PKL = MERGED_DATA_PKL # Should overwrite previous run



def merge_with_unchanged_data(new_data: pd.DataFrame):
    """
    Merge new preprocessed data into the previous merged database.

    Rules:
    - same hash → replace old row
    - new hash → append
    """

    # Case 1: first run ever
    if not os.path.exists(MERGED_DATA_PKL):
        logger.info("No previous merged_data.pkl found – creating new one")
        merged_database = new_data.copy()

    else:
        logger.info("Loading previous merged_data.pkl")
        old_data = pd.read_pickle(MERGED_DATA_PKL)

        for df_name, df in [("old_data", old_data), ("new_data", new_data)]:
            if "hash" not in df.columns:
                raise ValueError(f"'hash' column missing in {df_name}")

        # Use hash as dataset identity
        old_data = old_data.set_index("hash")
        new_data = new_data.set_index("hash")

        # Replace rows where hash already exists
        old_data.update(new_data)

        # Add rows with new hashes
        new_hashes = new_data.index.difference(old_data.index)
        merged_database = pd.concat(
            [old_data, new_data.loc[new_hashes]],
            axis=0
        )

        merged_database = merged_database.reset_index()

    # Final cleanup
    merged_database = merged_database.fillna("")

    # Persist
    merged_database.to_pickle(PIPELINE_OUTPUT_PKL)
    merged_database.to_csv(PIPELINE_OUTPUT_CSV, index=False)

    logger.info(f"Merged database now has {len(merged_database)} rows")


if __name__ == "__main__":
    """
    Is triggered by github action pipeline once all language files has been successfully generated by the translation stage.
    """
    lang_found = []
    # Detect pickle files for languages dynamically
    for lang in config.WORKFLOW_TRANSLATE_LANGUAGES:
        file_path = os.path.join(config.WORKFLOW_ARTIFACT_FOLDER, '{}_translated.pkl'.format(lang))
        if os.path.exists(file_path):
            lang_found.append(lang)

    # Process and merge files
    if len(lang_found) < 1:
        logger.error(f"Merge not possible, {lang_found} languages found" )

    if len(lang_found) == 1:
        lang = lang_found[0]
        df1 = pd.read_pickle(os.path.join(config.WORKFLOW_ARTIFACT_FOLDER,  '{}_translated.pkl'.format(lang)))
        logger.info(f"First language has {len(df1.index)} rows")

        merge_with_unchanged_data(df1)

    if len(lang_found) > 1:
        df1 = pd.read_pickle(os.path.join(config.WORKFLOW_ARTIFACT_FOLDER,  '{}_translated.pkl'.format(lang_found[0])))
        for lang in lang_found[1:]: # start from the second language
            translated_columns_to_add = config.WORKFLOW_MERGE_COLUMNS + [col_name + "_" + lang for col_name in config.WORKFLOW_TRANSLATE_COLUMNS]
            df2 = pd.read_pickle(os.path.join(config.WORKFLOW_ARTIFACT_FOLDER,  '{}_translated.pkl'.format(lang)))
            df1 = df1.merge(df2[translated_columns_to_add], on=config.WORKFLOW_MERGE_COLUMNS)
        
        logger.info(f"All languages combined have {len(df1.index)} rows")
        merge_with_unchanged_data(df1)
