
import logging
import logging.config
import os
import sys
from time import time

import pandas as pd

sys.path.append('../')
from pathlib import Path
import scraper.configuration as config

# Initialize and configure the logger
logging.config.dictConfig(config.LOGGING_CONFIG)
logger = logging.getLogger("Scraping log")

MERGED_DATA_PKL = Path("data/merged_data.pkl") # From Git
PIPELINE_OUTPUT_CSV = Path("merged_data.csv")
PIPELINE_OUTPUT_PKL = MERGED_DATA_PKL # Should overwrite previous run



def merge_with_unchanged_data(new_data: pd.DataFrame):
    """
    Merge new preprocessed data into the previous merged database.

    Rules:
    - same hash → replace old row
    - new hash → append
    """

    if "hash" not in new_data.columns:
        raise ValueError("new_data has no 'hash' column")

    if new_data["hash"].isna().any():
        raise ValueError("new_data contains rows with missing hash")

    if new_data.empty:
        logger.warning("merge called with empty new_data")
        return

    # Case 1: first run ever
    if not os.path.exists(MERGED_DATA_PKL):
        logger.info("No previous merged_data.pkl found – creating new one")
        merged_database = new_data.copy()

    else:
        logger.info("Loading previous merged_data.pkl")
        old_data = pd.read_pickle(MERGED_DATA_PKL)
        new_hashes = set(new_data["hash"].unique())
        old_data_filtered = old_data[~old_data["hash"].isin(new_hashes)]

        # Append new data
        merged_database = pd.concat(
            [old_data_filtered, new_data],
            ignore_index=True
        )

    # Append new data
    merged_database = pd.concat(
        [old_data_filtered, new_data],
        ignore_index=True
    )

    merged_database.to_pickle(PIPELINE_OUTPUT_PKL)
    merged_database.to_csv(PIPELINE_OUTPUT_CSV, index=False)

    logger.info(
        f"Merged database now has {len(merged_database)} rows "
        f"({merged_database['hash'].nunique()} datasets)"
    )



if __name__ == "__main__":
    """
    Is triggered by github action pipeline once all language files has been successfully generated by the translation stage.
    """
    lang_found = []
    # Detect pickle files for languages dynamically
    for lang in config.WORKFLOW_TRANSLATE_LANGUAGES:
        file_path = os.path.join(config.WORKFLOW_ARTIFACT_FOLDER, '{}_translated.pkl'.format(lang))
        if os.path.exists(file_path):
            lang_found.append(lang)

    # Process and merge files
    if len(lang_found) < 1:
        logger.error(f"Merge not possible, {lang_found} languages found" )

    if len(lang_found) == 1:
        lang = lang_found[0]
        df1 = pd.read_pickle(os.path.join(config.WORKFLOW_ARTIFACT_FOLDER,  '{}_translated.pkl'.format(lang)))
        logger.info(f"First language has {len(df1.index)} rows")

        merge_with_unchanged_data(df1)

    if len(lang_found) > 1:
        df1 = pd.read_pickle(os.path.join(config.WORKFLOW_ARTIFACT_FOLDER,  '{}_translated.pkl'.format(lang_found[0])))
        for lang in lang_found[1:]: # start from the second language
            translated_columns_to_add = config.WORKFLOW_MERGE_COLUMNS + [col_name + "_" + lang for col_name in config.WORKFLOW_TRANSLATE_COLUMNS]
            df2 = pd.read_pickle(os.path.join(config.WORKFLOW_ARTIFACT_FOLDER,  '{}_translated.pkl'.format(lang)))
            df1 = df1.merge(df2[translated_columns_to_add], on=config.WORKFLOW_MERGE_COLUMNS)
        
        logger.info(f"All languages combined have {len(df1.index)} rows")
        merge_with_unchanged_data(df1)
