# The preflight job quickly checks the availability of services and generates hashes for each dataset (layer) based on the fields "name, title, abstract, contact, keywords". Be aware that this needs adjusting if changes of other fields need to be watched too.

name: Preflight check & hash

on:
  workflow_dispatch:
  push:
    branches:
      - preflight_check
  schedule:
    - cron: "0 3 * * *" # optional daily run

permissions:
  contents: write # Needed for push to repo
  actions: read

jobs:
  preflight:
    runs-on: ubuntu-latest
    timeout-minutes: 330
    defaults:
      run:
        working-directory: ./scraper

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml pyproj OWSLib

      # TODO: Replace tiny_sources with sources.csv once stable!
      - name: Run preflight
        run: |
          python workflow/preflight_job.py \
            --input tiny_sources.csv \
            --out-diagnostics preflight-diagnostics.jsonl \
            --baseline-hashes preflight-diagnostics.jsonl || true

      - name: Upload preflight diagnostics
        uses: actions/upload-artifact@v4
        with:
          name: preflight-diagnostics
          path: "scraper/preflight-diagnostics.jsonl"

      - name: Upload preflight hashes
        uses: actions/upload-artifact@v4
        with:
          name: preflight-hashes
          path: "scraper/preflight-hashes.json"

  compare-hashes:
    needs: preflight
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scraper

    steps:
      - name: Checkout repository # Important to get the merged_data.pkl for comparison
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==1.5.2 numpy==1.24.3

      - name: Download preflight hashes artifact
        uses: actions/download-artifact@v4
        with:
          name: preflight-hashes
          path: artifacts

      - name: Download preflight diagnostics artifact
        uses: actions/download-artifact@v4
        with:
          name: preflight-diagnostics
          path: artifacts

      - name: Run hash comparison
        run: |
          python workflow/compare_preflight_merged.py

      - name: Upload datasets-to-process artifact
        uses: actions/upload-artifact@v4
        with:
          name: datasets-to-process
          path: scraper/datasets_to_process.json

  scrape-datasets:
    needs: compare-hashes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scraper

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests OWSLib pandas==1.5.2 numpy==1.24.3 pytz lxml pyproj

      - name: Download datasets-to-process artifact
        uses: actions/download-artifact@v4
        with:
          name: datasets-to-process
          path: artifacts

      - name: Run Python script
        run: |
          python workflow/scrape_job.py
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - uses: actions/upload-artifact@v4
        with:
          name: scrape_output_csv
          path: scraper/scrape_job_output.csv # From artifacts for 2nd stage
      - uses: actions/upload-artifact@v4
        with:
          name: scrape_output_pkl
          path: scraper/scrape_job_output.pkl # From artifacts for 2nd stage

  preprocess-datasets:
    needs: scrape-datasets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scraper

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download datasets-to-process artifact
        uses: actions/download-artifact@v4
        with:
          name: scrape_output_pkl
          path: artifacts

      - name: check dir
        run: |
          pwd
          ls -la
          ls artifacts

      # - name: Check scraper output
      #   run: |
      #     if [ ! -f "artifacts/scrape_job_output.pkl" ]; then
      #       echo "Scraper output missing. Skipping preprocessing."
      #       exit 1
      #     fi

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --force-reinstall -r workflow/requirements/requirements_preprocessing.txt
      - name: Download spacy models
        run: |
          python -m spacy download en_core_web_sm
          python -m spacy download fr_core_news_sm
          python -m spacy download de_core_news_sm
          python -m spacy download it_core_news_sm

      - name: Download nltk stopwords
        run: |
          python -m nltk.downloader all

      - name: Run Python script
        run: |
          python workflow/preprocess_job.py
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - uses: actions/upload-artifact@v4
        with:
          name: preprocessed_output_csv
          path: scraper/preprocessed_data.csv # From artifacts for 2nd stage
      - uses: actions/upload-artifact@v4
        with:
          name: preprocessed_output_pkl
          path: scraper/preprocessed_data.pkl # From artifacts for 2nd stage

  translate_de:
    needs: preprocess-datasets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scraper

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4 # May need additional pull directive

      - name: Increase git buffer size
        run: |
          git config --global http.postBuffer 1048576000

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r workflow/requirements/requirements_translation.txt

      - name: Download datasets-to-process artifact
        uses: actions/download-artifact@v4
        with:
          name: preprocessed_output_pkl
          path: artifacts

      - name: Translate DE
        run: |
          LANG_FROM_PIPELINE=${{'de'}} python ./workflow/translate_job.py

      - uses: actions/upload-artifact@v4
        with:
          name: de_translated
          path: ./scraper/artifacts/de_translated.pkl

      - uses: actions/upload-artifact@v4
        with:
          name: de_translated_csv
          path: ./scraper/artifacts/de_translated.csv

  translate_en:
    needs: preprocess-datasets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scraper

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Increase git buffer size
        run: |
          git config --global http.postBuffer 1048576000

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r workflow/requirements/requirements_translation.txt

      - name: Download datasets-to-process artifact
        uses: actions/download-artifact@v4
        with:
          name: preprocessed_output_pkl
          path: artifacts

      - name: Translate EN
        run: |
          LANG_FROM_PIPELINE=${{'en'}} python ./workflow/translate_job.py

      - uses: actions/upload-artifact@v4
        with:
          name: en_translated.pkl
          path: ./scraper/artifacts/

      - uses: actions/upload-artifact@v4
        with:
          name: en_translated_csv
          path: ./scraper/artifacts/en_translated.csv

  translate_fr:
    needs: preprocess-datasets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scraper

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Increase git buffer size
        run: |
          git config --global http.postBuffer 1048576000

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r workflow/requirements/requirements_translation.txt

      - name: Download datasets-to-process artifact
        uses: actions/download-artifact@v4
        with:
          name: preprocessed_output_pkl
          path: artifacts

      - name: Translate FR
        run: |
          LANG_FROM_PIPELINE=${{'fr'}} python ./workflow/translate_job.py

      - uses: actions/upload-artifact@v4
        with:
          name: fr_translated
          path: ./scraper/artifacts/fr_translated.pkl

      - uses: actions/upload-artifact@v4
        with:
          name: fr_translated_csv
          path: ./scraper/artifacts/fr_translated.csv

  translate_it:
    needs: preprocess-datasets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scraper

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Increase git buffer size
        run: |
          git config --global http.postBuffer 1048576000

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r workflow/requirements/requirements_translation.txt

      - name: Download datasets-to-process artifact
        uses: actions/download-artifact@v4
        with:
          name: preprocessed_output_pkl
          path: artifacts

      - name: Translate IT
        run: |
          LANG_FROM_PIPELINE=${{'it'}} python ./workflow/translate_job.py

      - uses: actions/upload-artifact@v4
        with:
          name: it_translated
          path: ./scraper/artifacts/it_translated.pkl

      - uses: actions/upload-artifact@v4
        with:
          name: it_translated_csv
          path: ./scraper/artifacts/it_translated.csv

  merge:
    needs: # Disable any languages/translate-jobs you don't need
      - translate_de
      - translate_en
      - translate_it
      - translate_fr
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scraper

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch full history so pushes work

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==1.5.2 numpy==1.24.3

      - uses: actions/download-artifact@v4
        with:
          path: ./scraper/artifacts/
          merge-multiple: true

      - name: Merge Databases
        run: |
          python ./workflow/merge_job.py

      - uses: actions/upload-artifact@v4
        with:
          name: merged_data_csv
          path: scraper/merged_data.csv

      - uses: actions/upload-artifact@v4
        with:
          name: merged_data_pkl
          path: scraper/data/merged_data.pkl

        # TODO: CHANGE BRANCH to main
      - name: Commit merged data to repository
        if: github.ref == 'refs/heads/preflight_check'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/merged_data.pkl

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update merged dataset (pipeline)"
            git push origin preflight_check
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
