name: Run geocat scraper and preprocessing

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly (every Sunday at midnight)
  workflow_dispatch:     # Allows manual execution from GitHub Actions tab

permissions:
  contents: write

jobs:
  scrape_geocat:   # ← job names cannot contain spaces
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scraper

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          ref: geocat_integration 

      - name: Increase git buffer size
        run: git config --global http.postBuffer 1048576000

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --force-reinstall -r requirements_geocat.txt

      - name: Run geocat scraper
        run: python scraper_geocat.py
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - name: Pull latest changes
        run: |
          git config pull.rebase true
          git pull origin geocat_integration

      - name: Upload geocat_metadata (PKL)
        uses: actions/upload-artifact@v4
        with:
          name: data_to_keep
          path: ./scraper/data/geocat_data/geocat_metadata.pkl

      
      - name: Push log files to repo
        uses: github-actions-x/commit@v2.9
        with:
      
          push-branch: "geocat_integration"
          commit-message: "geocat_data"
          force-add: "true"
          files: ./scraper/data/geocat_data/
          name: autoupdate
